version: "3"
services:
  nginx:
    ports:
    - "80:80"
    volumes:
    - "static:/var/simplesamlphp/public/:ro"
    - "./configuration/nginx.conf:/etc/nginx/nginx.conf:ro"
    container_name: "nginx"
    image: "nginx:1.25"
  phpfpm:
    volumes:
    - "static:/var/simplesamlphp/public/:ro"
    - ".storage/config/:/var/simplesamlphp/config/"
    - ".storage/metadata/:/var/simplesamlphp/metadata/"
    - ".storage/cert/:/var/simplesamlphp/cert/"
    container_name: "phpfpm"
    build:
      context: .
      dockerfile: dockerfiles/phpfpm.dockerfile
volumes:
  static:
    driver: local
